apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ops5-alerts
  namespace: default
  labels:
    release: monitoring
spec:
  groups:
    - name: minecraft.rules
      rules:
        - alert: PodCrashLooping
          # It can take a long time for a single loop to happen, sometimes upward of 2 minutes in a simple OOM scenario. So these are set to high numbers.
          expr: increase(kube_pod_container_status_restarts_total{namespace="default"}[10m]) > 3
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{ $labels.pod }} is crash looping"
            runbook: |
              See the Alert 1 runbook in the Ops 5 document.

        - alert: HighNodeCPU
          expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Node CPU usage above 80% for 2 minutes"
            runbook: |
              See the Alert 2 runbook in the Ops 5 document.

        - alert: MinecraftStatusUnhealthyOrMissing
          expr: |
            (minecraft_status_healthy{namespace="default", condition="true"} == 0)
            OR
            (absent(minecraft_status_healthy{namespace="default", condition="true"}) == 1)
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Minecraft server is unhealthy or metrics are missing"
            runbook: |
              See the Alert 3 runbook in the Ops 5 document.

