apiVersion: batch/v1
kind: Job
metadata:
  name: minecraft-restore
  namespace: default
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: restore-worker
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Installing tools..."
              apk add --no-cache aws-cli tar
              
              echo "Cleaning out existing stale world data..."
              rm -rf /opt/minecraft/world/*
              
              echo "Downloading backup from S3..."
              aws s3 cp s3://cs312-wengor-minecraft-backups/backups/world-backup.tar.gz /tmp/world-backup.tar.gz
              
              echo "Extracting backup into the persistent volume..."
              tar -xzf /tmp/world-backup.tar.gz -C /opt/minecraft/world
              
              echo "Restore process successfully completed!"
          volumeMounts:
            - name: minecraft-volume
              mountPath: /opt/minecraft/world
      volumes:
        - name: minecraft-volume
          persistentVolumeClaim:
            claimName: minecraft-pvc # Must match your live volume claim
