---
- name: Set up k3s
  user: ubuntu
  hosts: all
  become: true

  tasks:
    - name: Ensure system dependencies are installed
      apt:
        name:
          - curl
          - sudo
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Download and run k3s installation script
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s # Prevents rerun if k3s is already installed

    # Install Helm, Prometheus, and Grafana
    # Based on installation we used in lab
    - name: Add Prometheus community Helm repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Idempotent deployment of kube-prometheus-stack
      kubernetes.core.helm:
        name: monitoring
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: default
        state: present # <-- This ensures it installs if missing, or upgrades only if values change
        wait: true
        values:
          grafana:
            service:
              type: NodePort
              nodePort: 31000
            sidecar:
              image:
                tag: "1.28.0"
          prometheus:
            prometheusSpec:
              serviceMonitorSelectorNilUsesHelmValues: false
              ruleSelectorNilUsesHelmValues: false
              retentionSize: "3GiB"
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
